site_name: Foundations
theme: readthedocs
docs_dir: api_docs/sources
repo_url: https://github.com/DeepLearnI/foundations
site_description: 'Documentation for Foundations, a platform for end-to-end machine learning. Created by Dessa.'

dev_addr: '0.0.0.0:8000'

pages:
- Home: index.md
- Creating stages: stage_creation.md
- Useful functions: ready_code.md
- Running stages: stages_running.md
- Tracking a deployment: deployment.md
- Getting job metrics: job_metrics.md
