results_config:
  redis_end_point: redis://${LOCAL_DOCKER_SCHEDULER_HOST}:6379
cache_config:
  end_point: /cache_end_point
container_config_root: ${FOUNDATIONS_HOME}/config/local_docker_scheduler/worker_config
job_deployment_env: local_docker_scheduler_plugin
job_results_root: ${FOUNDATIONS_HOME}/job_data
scheduler_url: http://${LOCAL_DOCKER_SCHEDULER_HOST}:5000
working_dir_root: ${FOUNDATIONS_HOME}/config/local_docker_scheduler/work_dir
