apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: foundations-model-package-${model_name}
  name: foundations-model-package-deployment-${model_name}
  namespace: foundations-scheduler-test
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: foundations-model-package-${model_name}
  template:
    metadata:
      labels: 
        app: foundations-model-package-${model_name}
    spec:
      nodeSelector:
        modelServer: "True"
      containers:
      - image: docker.shehanigans.net/foundations-model-package
        imagePullPolicy: Always
        env:
          - name: JOB_ID
            value: "${job_id}"
        resources:
          limits:
            nvidia.com/gpu: 1
        name: model
        volumeMounts:
        - mountPath: /archive
          name: archive
      volumes: 
        - name: 'archive'
          persistentVolumeClaim: 
            claimName: 'archive-storage'
      imagePullSecrets:
      - name: dessa-registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: foundations-model-package-${model_name}
  namespace: foundations-scheduler-test
spec:
  selector:
    app: foundations-model-package-${model_name}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
