cache_implementation:
  cache_type: foundations_gcp.GCPCacheBackend
  constructor_arguments: [result-test]

archive_listing_implementation:
  archive_listing_type: foundations_gcp.GCPPipelineArchiveListing
  constructor_arguments: [result-test]

project_listing_implementation:
  project_listing_type: foundations_gcp.GCPPipelineArchiveListing
  constructor_arguments: [result-projects-names]

stage_log_archive_implementation:
  archive_type: foundations_gcp.GCPPipelineArchive
  constructor_arguments: [result-test]

persisted_data_archive_implementation:
  archive_type: foundations_gcp.GCPPipelineArchive
  constructor_arguments: [result-test]

provenance_archive_implementation:
  archive_type: foundations_gcp.GCPPipelineArchive
  constructor_arguments: [result-test]

job_source_archive_implementation:
  archive_type: foundations_gcp.GCPPipelineArchive
  constructor_arguments: [result-test]

artifact_archive_implementation:
  archive_type: foundations_gcp.GCPPipelineArchive
  constructor_arguments: [result-test]

miscellaneous_archive_implementation:
  archive_type: foundations_gcp.GCPPipelineArchive
  constructor_arguments: [result-test]

deployment_implementation:
  deployment_type: foundations_gcp.GCPJobDeployment
  constructor_arguments: [code-test, result-test]

