cache_implementation:
  cache_type: foundations.GCPCacheBackend
  constructor_arguments: [tango-result-test]

archive_listing_implementation:
  archive_listing_type: foundations.GCPPipelineArchiveListing
  constructor_arguments: [tango-result-test]

stage_log_archive_implementation:
  archive_type: foundations.GCPPipelineArchive
  constructor_arguments: [tango-result-test]

persisted_data_archive_implementation:
  archive_type: foundations.GCPPipelineArchive
  constructor_arguments: [tango-result-test]

provenance_archive_implementation:
  archive_type: foundations.GCPPipelineArchive
  constructor_arguments: [tango-result-test]

job_source_archive_implementation:
  archive_type: foundations.GCPPipelineArchive
  constructor_arguments: [tango-result-test]

artifact_archive_implementation:
  archive_type: foundations.GCPPipelineArchive
  constructor_arguments: [tango-result-test]

miscellaneous_archive_implementation:
  archive_type: foundations.GCPPipelineArchive
  constructor_arguments: [tango-result-test]

deployment_implementation:
  deployment_type: foundations.GCPJobDeployment
  constructor_arguments: [tango-code-test, tango-result-test]