archive_listing_implementation:
  archive_listing_type: &listing_implementation !!python/name:foundations_contrib.local_file_system_pipeline_listing.LocalFileSystemPipelineListing ''
  constructor_arguments: [/tmp/foundations-archive]

artifact_archive_implementation:
  archive_type: &archive_implementation !!python/name:foundations_contrib.local_file_system_pipeline_archive.LocalFileSystemPipelineArchive ''
  constructor_arguments: [/tmp/foundations-archive]

cache_implementation:
  cache_type: !!python/name:foundations_contrib.local_file_system_cache_backend.LocalFileSystemCacheBackend ''
  constructor_arguments: [/tmp/foundations-cache]

deployment_implementation: {deployment_type: !!python/name:foundations_contrib.local_shell_job_deployment.LocalShellJobDeployment ''}

job_source_archive_implementation:
  archive_type: *archive_implementation
  constructor_arguments: [/tmp/foundations-archive]

miscellaneous_archive_implementation:
  archive_type: *archive_implementation
  constructor_arguments: [/tmp/foundations-archive]

persisted_data_archive_implementation:
  archive_type: *archive_implementation
  constructor_arguments: [/tmp/foundations-archive]

project_listing_implementation:
  constructor_arguments: [/tmp/projects]
  project_listing_type: *listing_implementation

provenance_archive_implementation:
  archive_type: *archive_implementation
  constructor_arguments: [/tmp/foundations-archive]

stage_log_archive_implementation:
  archive_type: *archive_implementation
  constructor_arguments: [/tmp/foundations-archive]

redis_url: redis://localhost:6379
