archive_listing_implementation:
  archive_listing_type: &listing_implementation !!python/name:foundations_contrib.local_file_system_pipeline_listing.LocalFileSystemPipelineListing ''
  constructor_arguments: [/tmp/foundations-archive]


cache_implementation:
  cache_type: !!python/name:foundations_contrib.local_file_system_cache_backend.LocalFileSystemCacheBackend ''
  constructor_arguments: [/tmp/foundations-cache]

deployment_implementation: {deployment_type: !!python/name:foundations_contrib.local_shell_job_deployment.LocalShellJobDeployment ''}

artifact_archive_implementation: &archive_implementation
  archive_type: !!python/name:foundations_contrib.local_file_system_pipeline_archive.LocalFileSystemPipelineArchive ''
  constructor_arguments: [/tmp/foundations-archive]

job_source_archive_implementation: *archive_implementation
miscellaneous_archive_implementation: *archive_implementation
persisted_data_archive_implementation: *archive_implementation
provenance_archive_implementation: *archive_implementation
stage_log_archive_implementation: *archive_implementation

project_listing_implementation:
  project_listing_type: *listing_implementation
  constructor_arguments: [/tmp/projects]

redis_url: redis://localhost:6379
