#Add this .config.yaml to the folder or link it to the script where you're fetching your results 
#for a job deployed on ssh

archive_listing_implementation:
  archive_listing_type: foundations_ssh.SFTPListing

stage_log_archive_implementation:
  archive_type: foundations_ssh.MultiSFTPBundledPipelineArchive

persisted_data_archive_implementation:
  archive_type: foundations_ssh.MultiSFTPBundledPipelineArchive

provenance_archive_implementation:
  archive_type: foundations_ssh.MultiSFTPBundledPipelineArchive

job_source_archive_implementation:
  archive_type: foundations_ssh.MultiSFTPBundledPipelineArchive

artifact_archive_implementation:
  archive_type: foundations_ssh.MultiSFTPBundledPipelineArchive

miscellaneous_archive_implementation:
  archive_type: foundations_ssh.MultiSFTPBundledPipelineArchive

project_listing_implementation:
  project_listing_type: foundations.bucket_pipeline_listing.BucketPipelineListing
  constructor_arguments: [!!python/name:foundations_ssh.sftp_bucket.SFTPBucket, /home/lou/mount/testbed/projects]

remote_user: lou
remote_host: 422.428.428.42
port: 22222
shell_command: /bin/bash
code_path: /home/lou/mount/testbed/jobs
result_path: /home/lou/mount/testbed/results
key_path: <key_path>
