#Add this .config.yaml to the folder or link it to the script where you're running the job you're deploying on ssh

cache_implementation:
  cache_type: foundations.LocalFileSystemCacheBackend
  constructor_arguments: [/tmp/foundations-cache]

archive_listing_implementation:
  archive_listing_type: foundations.LocalFileSystemPipelineListing

stage_log_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive

persisted_data_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive

provenance_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive

job_source_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive

artifact_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive

miscellaneous_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive

project_listing_implementation:
  project_listing_type: foundations.bucket_pipeline_listing.BucketPipelineListing
  constructor_arguments: [!!python/name:foundations_ssh.sftp_bucket.SFTPBucket , /home/lou/mount/testbed/projects]

deployment_implementation:
  deployment_type: foundations_ssh.SFTPJobDeployment

redis_url: redis://422.428.428.42:33333

remote_user: lou
remote_host: 422.428.428.42
port: 22222
shell_command: /bin/bash
code_path: /home/lou/mount/testbed/jobs
result_path: /home/lou/mount/testbed/results
key_path: <key_path>

log_level: DEBUG
