
# Copyright (C) DeepLearning Financial Technologies Inc. - All Rights Reserved
# Unauthorized copying, distribution, reproduction, publication, use of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Thomas Rogers <t.rogers@dessa.com>, 06 2018



# This file contains the configurations used by Foundations to define, for example,
# where to deploy a job and store its results for a local job deployment.  Feel free to have a look at this file,
# but know that a machine learning engineer will never need to create one.  That
# responsibility falls to a user who wishes to create or configure an integration
# with an execution environment (e.g. GCP, remote machine) or remote storage (e.g.
# S3, GS) on a machine learning engineer's behalf.

# Usually, this information will be provided for the machine learning engineer by
# the installer / integrator of Foundations in the form of a configuration yaml.
# Foundations will automatically parse that yaml prior to and during job deployment.


cache_implementation:
  cache_type: foundations.LocalFileSystemCacheBackend
  constructor_arguments: [/tmp/foundations-cache]

archive_listing_implementation:
  archive_listing_type: foundations.LocalFileSystemPipelineListing
  constructor_arguments: [/tmp/archives]

stage_log_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/archives]

persisted_data_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/archives]

provenance_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/archives]

job_source_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/archives]

artifact_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/archives]

miscellaneous_archive_implementation:
  archive_type: foundations.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/archives]

project_listing_implementation:
  project_listing_type: foundations.LocalFileSystemPipelineListing
  constructor_arguments: [/tmp/projects]


deployment_implementation:
  deployment_type: foundations.LocalShellJobDeployment