---
  
- name: Install ansible dependencies
  gather_facts: False
  hosts: "{{ instance_name }}"
  become: yes  
  tasks:
    - name: install python-apt
      shell: apt-get install -y python-apt
      retries: 10
      delay: 30
      register: result
      until: result is success

- name: Upload files needed for the installation
  copy:
    src: ./local_scheduler_instance/*
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Login and Pull Docker Images
  hosts: "{{ instance_name }}"
  become: yes
  tasks:
    - name : Generating Configuration Files
      shell: /home/ubuntu/gen_default_config.py

    - name : Login Docker
      shell: docker login docker.shehanigans.net -u {{ NEXUS_USER }} -p {{ NEXUS_PASSWORD }}
    
    - name : Pull Orbit Worker Images
      shell: docker pull docker.shehanigans.net/orbit/worker:latest
    - name : Retag Orbit Worker Images
      shell: docker tag docker-staging.shehanigans.net/orbit/worker:latest orbit/worker:latest
      
    - name : Pull Atlas Worker Images
      shell: docker pull docker.shehanigans.net/atlas-ce/worker:latest
    - name : Retag Atlas Worker Images
      shell: docker pull docker-staging.shehanigans.net/atlas-ce/worker:latest atlas-ce/worker:latest
