---
  
- name: Install ansible dependencies
  gather_facts: False
  hosts: "{{ instance_name }}"
  become: yes  
  tasks:
    - name: install python-apt
      shell: apt-get install -y python-apt
      retries: 10
      delay: 30
      register: result
      until: result is success

- name: Upload files needed for the installation
  copy:
    src: /srv/myfiles/foo.conf
    dest: /etc/foo.conf
    owner: foo
    group: foo
    mode: '0644'

- name: Login and Pull Docker Images
  hosts: "{{ instance_name }}"
  become: yes
  tasks:
    - name : Load All Docker Images needed
      shell: /home/ubuntu/scheduler_installer.py -N -i 

    - name : Login Docker
      shell: docker login docker.shehanigans.net -u {{ NEXUS_USER }} -p {{ NEXUS_PASSWORD }}
    - name : Login Docker staging
      shell: docker login docker-staging.shehanigans.net -u {{ NEXUS_USER }} -p {{ NEXUS_PASSWORD }}
    
    - name : Pull Orbit Worker Images
      shell: docker pull docker-staging.shehanigans.net/orbit/worker:latest
    - name : Retag Orbit Worker Images
      shell: docker tag docker-staging.shehanigans.net/orbit/worker:latest orbit/worker:latest
      
    - name : Pull Atlas Worker Images
      shell: docker pull docker-staging.shehanigans.net/atlas-ce/worker:latest
    - name : Retag Atlas Worker Images
      shell: docker pull docker-staging.shehanigans.net/atlas-ce/worker:latest atlas-ce/worker:latest
    
    - name : 'Using Scheduler Installer to setup configs'
      shell: /home/ubuntu/scheduler_installer.py -N -c 