archive_listing_implementation:
  archive_listing_type: !!python/name:vcat.local_file_system_pipeline_listing.LocalFileSystemPipelineListing ''
  constructor_arguments: [/tmp/archives]
artifact_archive_implementation:
  archive_type: &id001 !!python/name:vcat.local_file_system_pipeline_archive.LocalFileSystemPipelineArchive ''
  constructor_arguments: [/tmp/archives]
cache_implementation:
  cache_type: !!python/name:vcat.local_file_system_cache_backend.LocalFileSystemCacheBackend ''
  constructor_arguments: [/tmp]
deployment_implementation: {deployment_type: !!python/name:vcat.local_shell_job_deployment.LocalShellJobDeployment ''}
job_source_archive_implementation:
  archive_type: *id001
  constructor_arguments: [/tmp/archives]
miscellaneous_archive_implementation:
  archive_type: *id001
  constructor_arguments: [/tmp/archives]
persisted_data_archive_implementation:
  archive_type: *id001
  constructor_arguments: [/tmp/archives]
provenance_archive_implementation:
  archive_type: *id001
  constructor_arguments: [/tmp/archives]
stage_log_archive_implementation:
  archive_type: *id001
  constructor_arguments: [/tmp/archives]
