cache_implementation:
  cache_type: vcat.LocalFileSystemCacheBackend
  constructor_arguments: [/tmp/foundations-cache]

archive_listing_implementation:
  archive_listing_type: vcat.LocalFileSystemPipelineListing
  constructor_arguments: [/tmp/foundations-archive]

stage_log_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/foundations-archive]

persisted_data_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/foundations-archive]

provenance_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/foundations-archive]

job_source_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/foundations-archive]

artifact_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/foundations-archive]

miscellaneous_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive
  constructor_arguments: [/tmp/foundations-archive]

deployment_implementation:
  deployment_type: vcat.LocalShellJobDeployment

job_source_bundle:
  bundle_name: test_bundle
  target_path: .
