########################## RUN LOCALLY

# cache_implementation:
#   cache_type: vcat.LocalFileSystemCacheBackend
#   constructor_arguments: [/tmp/foundations-cache]

# archive_listing_implementation:
#   archive_listing_type: vcat.LocalFileSystemPipelineListing
#   constructor_arguments: [/tmp/foundations-archive]

# stage_log_archive_implementation:
#   archive_type: vcat.LocalFileSystemPipelineArchive
#   constructor_arguments: [/tmp/foundations-archive]

# persisted_data_archive_implementation:
#   archive_type: vcat.LocalFileSystemPipelineArchive
#   constructor_arguments: [/tmp/foundations-archive]

# provenance_archive_implementation:
#   archive_type: vcat.LocalFileSystemPipelineArchive
#   constructor_arguments: [/tmp/foundations-archive]

# job_source_archive_implementation:
#   archive_type: vcat.LocalFileSystemPipelineArchive
#   constructor_arguments: [/tmp/foundations-archive]

# artifact_archive_implementation:
#   archive_type: vcat.LocalFileSystemPipelineArchive
#   constructor_arguments: [/tmp/foundations-archive]

# miscellaneous_archive_implementation:
#   archive_type: vcat.LocalFileSystemPipelineArchive
#   constructor_arguments: [/tmp/foundations-archive]

# deployment_implementation:
#   deployment_type: vcat.LocalShellJobDeployment

########################## RUN ON GCP

# cache_implementation:
#   cache_type: vcat_gcp.GCPCacheBackend
#   constructor_arguments: [tango-result-test]

# archive_listing_implementation:
#   archive_listing_type: vcat_gcp.GCPPipelineArchiveListing
#   constructor_arguments: [tango-result-test]

# stage_log_archive_implementation:
#   archive_type: vcat_gcp.GCPPipelineArchive
#   constructor_arguments: [tango-result-test]

# persisted_data_archive_implementation:
#   archive_type: vcat_gcp.GCPPipelineArchive
#   constructor_arguments: [tango-result-test]

# provenance_archive_implementation:
#   archive_type: vcat_gcp.GCPPipelineArchive
#   constructor_arguments: [tango-result-test]

# job_source_archive_implementation:
#   archive_type: vcat_gcp.GCPPipelineArchive
#   constructor_arguments: [tango-result-test]

# artifact_archive_implementation:
#   archive_type: vcat_gcp.GCPPipelineArchive
#   constructor_arguments: [tango-result-test]

# miscellaneous_archive_implementation:
#   archive_type: vcat_gcp.GCPPipelineArchive
#   constructor_arguments: [tango-result-test]

# deployment_implementation:
#   deployment_type: vcat_gcp.GCPJobDeployment
#   constructor_arguments: [tango-code-test, tango-result-test]

############################## RUN ON MOCK BELL

cache_implementation:
  cache_type: vcat.LocalFileSystemCacheBackend
  constructor_arguments: [/tmp/foundations-cache]

archive_listing_implementation:
  archive_listing_type: vcat.LocalFileSystemPipelineListing

stage_log_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive

persisted_data_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive

provenance_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive

job_source_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive

artifact_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive

miscellaneous_archive_implementation:
  archive_type: vcat.LocalFileSystemPipelineArchive

deployment_implementation:
  deployment_type: vcat_ssh.SFTPJobDeployment

remote_user: ja
remote_host: 192.168.128.58
shell_command: /bin/bash
code_path: /home/ja/jobs
result_path: /home/ja/job_results
key_path: ./bare_metal.pem